name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      PORT: 4000
      NODE_ENV: production
      PRIVATE_KEY: ${{ secrets.PRIVATEKEY }}
      MONGO_URL: ${{ secrets.URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}

      - name: Build Docker Image
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.pro.yml build

      - name: Push Docker Image
        run: |
          docker tag my-app ${{ secrets.USER }}/abbas:latest
          docker push ${{ secrets.USER }}/abbas:latest
