on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      PORT: 4000
      NODE_ENV: production
      privatekey: ${{ secrets.PRIVATEKEY }}
      Url: ${{ secrets.URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.USER}}

          password: ${{secrets.TOKEN}}

      - name: Build Docker Image
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml build

      - name: Push Docker Image
        run: |
          docker push ${{secrets.USER}}/abbas:latest
